/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.FramePanel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import trainingcentersystem.Validation;
import trainingcentersystem.Student;

/**
 *
 * @author DELL
 */
public class AssignGrades extends javax.swing.JPanel {

    /**
     * Creates new form assignGrades
     */
    private void setColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(0,64,128));
    }
    private void getColor(JPanel p)
    {
        p.setBackground(new java.awt.Color(105,105,105));
    }
    public AssignGrades() {
        initComponents();
        jPanelWrongCourseWork.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelWrongFinalExam.setVisible(false);
        jPanelwrongMidTerm.setVisible(false);
        jTextFieldID.setEditable(false);
        jTextFieldgpa.setEditable(false);
        jTextFieldName.setEditable(false);
        jComboBoxResgisteredCourse.setEnabled(false);
        jTextFieldCourseWork.setEnabled(false);
        jTextFieldFinal.setEnabled(false);
        jTextFieldMidTerm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxLevel = new javax.swing.JComboBox<>();
        jComboBoxDepart = new javax.swing.JComboBox<>();
        jTextFieldGPA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIDAdminSearch = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelSuccessOrFail = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxLevel1 = new javax.swing.JComboBox<>();
        jComboBoxDepart1 = new javax.swing.JComboBox<>();
        jTextFieldgpa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxResgisteredCourse = new javax.swing.JComboBox<>();
        jTextFieldMidTerm = new javax.swing.JTextField();
        jTextFieldCourseWork = new javax.swing.JTextField();
        jTextFieldFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanelWrongFinalExam = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelWrongCourseWork = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanelwrongMidTerm = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanelWrongSearchKey = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelSearch = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelReset = new javax.swing.JLabel();

        jLabel9.setText("GPA");

        jLabel10.setText("Department");

        jComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", "Level 4" }));

        jComboBoxDepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SWE","CS","IS","IT" }));

        jLabel8.setText("Level");

        setBackground(new java.awt.Color(105, 105, 105));

        jTextFieldIDAdminSearch.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jTextFieldIDAdminSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIDAdminSearch.setBorder(null);
        jTextFieldIDAdminSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDAdminSearchActionPerformed(evt);
            }
        });

        jTextFieldID.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldID.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID ");

        jTextFieldName.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldName.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabelSuccessOrFail.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabelSuccessOrFail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSuccessOrFail.setText("Search For Student ... !");

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Student");

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("GPA");

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Department");

        jComboBoxLevel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jComboBoxDepart1.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxDepart1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jTextFieldgpa.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldgpa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldgpa.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Level");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("your resgistered Courses");

        jComboBoxResgisteredCourse.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jComboBoxResgisteredCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxResgisteredCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResgisteredCourseActionPerformed(evt);
            }
        });

        jTextFieldMidTerm.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldMidTerm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMidTerm.setBorder(null);

        jTextFieldCourseWork.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldCourseWork.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCourseWork.setBorder(null);
        jTextFieldCourseWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCourseWorkActionPerformed(evt);
            }
        });

        jTextFieldFinal.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextFieldFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFinal.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Course Work");

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mid Term Exam");

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Final Exam");

        jPanelWrongFinalExam.setBackground(new java.awt.Color(105, 105, 105));

        jLabel17.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel17.setText("Wrong Final Exam");

        javax.swing.GroupLayout jPanelWrongFinalExamLayout = new javax.swing.GroupLayout(jPanelWrongFinalExam);
        jPanelWrongFinalExam.setLayout(jPanelWrongFinalExamLayout);
        jPanelWrongFinalExamLayout.setHorizontalGroup(
            jPanelWrongFinalExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongFinalExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongFinalExamLayout.setVerticalGroup(
            jPanelWrongFinalExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongFinalExamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanelWrongCourseWork.setBackground(new java.awt.Color(105, 105, 105));

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel15.setText("Wrong Course Work");

        javax.swing.GroupLayout jPanelWrongCourseWorkLayout = new javax.swing.GroupLayout(jPanelWrongCourseWork);
        jPanelWrongCourseWork.setLayout(jPanelWrongCourseWorkLayout);
        jPanelWrongCourseWorkLayout.setHorizontalGroup(
            jPanelWrongCourseWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongCourseWorkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongCourseWorkLayout.setVerticalGroup(
            jPanelWrongCourseWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongCourseWorkLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jPanelwrongMidTerm.setBackground(new java.awt.Color(105, 105, 105));

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel16.setText("Wrong Mid Term Exam");

        javax.swing.GroupLayout jPanelwrongMidTermLayout = new javax.swing.GroupLayout(jPanelwrongMidTerm);
        jPanelwrongMidTerm.setLayout(jPanelwrongMidTermLayout);
        jPanelwrongMidTermLayout.setHorizontalGroup(
            jPanelwrongMidTermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwrongMidTermLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelwrongMidTermLayout.setVerticalGroup(
            jPanelwrongMidTermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelwrongMidTermLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16))
        );

        jPanelWrongSearchKey.setBackground(new java.awt.Color(105, 105, 105));

        jLabel18.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cancel_20px.png"))); // NOI18N
        jLabel18.setText("Wrong Course Key");

        javax.swing.GroupLayout jPanelWrongSearchKeyLayout = new javax.swing.GroupLayout(jPanelWrongSearchKey);
        jPanelWrongSearchKey.setLayout(jPanelWrongSearchKeyLayout);
        jPanelWrongSearchKeyLayout.setHorizontalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelWrongSearchKeyLayout.setVerticalGroup(
            jPanelWrongSearchKeyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWrongSearchKeyLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18))
        );

        jPanel1.setBackground(new java.awt.Color(105, 105, 105));

        jLabel14.setBackground(new java.awt.Color(105, 105, 105));
        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Create_Archive_96px.png"))); // NOI18N
        jLabel14.setText("Assign Grades");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Search");

        jLabel20.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Reset");

        jPanel2.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelSearch.setBackground(java.awt.SystemColor.controlDkShadow);
        jLabelSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Find_and_Replace_96px.png"))); // NOI18N
        jLabelSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.SystemColor.controlDkShadow);

        jLabelReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Reset_96px.png"))); // NOI18N
        jLabelReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelResetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReset, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIDAdminSearch)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(295, 295, 295))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(48, 48, 48)
                                                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jComboBoxLevel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(41, 41, 41)
                                                    .addComponent(jTextFieldgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBoxResgisteredCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                    .addComponent(jComboBoxDepart1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextFieldFinal)
                                                        .addComponent(jTextFieldMidTerm)
                                                        .addComponent(jTextFieldCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelWrongFinalExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelwrongMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelWrongCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(418, 418, 418))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabelSuccessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIDAdminSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanelWrongSearchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12)
                                .addComponent(jComboBoxDepart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxResgisteredCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelWrongCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jPanelwrongMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCourseWork, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(2, 2, 2)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanelWrongFinalExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDAdminSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDAdminSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDAdminSearchActionPerformed
    private void setPanel(Student x)
    {
        jTextFieldgpa.setText(""+x.getGPA());
        jTextFieldID.setText(""+x.getID());
        jTextFieldName.setText(""+x.getName());
        String subject[]=x.getCourses();
        jComboBoxResgisteredCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { subject[0],subject[1],subject[2],subject[3],subject[4],subject[5],subject[6]  }));
        jComboBoxDepart1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{x.getDepart()}));
        int level = x.getLevel();
        if(level==1)
            jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Level 1"}));
        else if(level==2)
            jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Level 2"}));
        else if (level==3)
            jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Level 3"}));
        else if(level==4)
            jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Level 4"}));

    }
    private void resetPanel()
    {
        jTextFieldID.setText("");
        jTextFieldIDAdminSearch.setText("");
        jTextFieldName.setText("");
        jTextFieldgpa.setText("");
        jComboBoxLevel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        jComboBoxResgisteredCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBoxDepart1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        
        jTextFieldCourseWork.setText("");
        jTextFieldFinal.setText("");
        jTextFieldMidTerm.setText("");
        jComboBoxResgisteredCourse.setEnabled(false);
        jPanelWrongCourseWork.setVisible(false);
        jPanelWrongFinalExam.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelwrongMidTerm.setVisible(false);
        
        jTextFieldCourseWork.setEnabled(false);
        jTextFieldFinal.setEnabled(false);
        jTextFieldMidTerm.setEnabled(false);


    }
    private void jTextFieldCourseWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCourseWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCourseWorkActionPerformed

    private void jComboBoxResgisteredCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResgisteredCourseActionPerformed
        // TODO add your handling code here:
        Student x = new Student();
        x=x.getStudent(Integer.parseInt(jTextFieldIDAdminSearch.getText()));
        if(x!=null){
            
            double grades[]=x.getGrades();
            if(jComboBoxResgisteredCourse.getSelectedIndex()==0){
                jTextFieldCourseWork.setText(""+grades[0]);
                jTextFieldMidTerm.setText(""+grades[1]);
                jTextFieldFinal.setText(""+grades[2]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==1){
                jTextFieldCourseWork.setText(""+grades[3]);
                jTextFieldMidTerm.setText(""+grades[4]);
                jTextFieldFinal.setText(""+grades[5]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==2){
                jTextFieldCourseWork.setText(""+grades[6]);
                jTextFieldMidTerm.setText(""+grades[7]);
                jTextFieldFinal.setText(""+grades[8]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==3){
                jTextFieldCourseWork.setText(""+grades[9]);
                jTextFieldMidTerm.setText(""+grades[10]);
                jTextFieldFinal.setText(""+grades[11]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==4){
                jTextFieldCourseWork.setText(""+grades[12]);
                jTextFieldMidTerm.setText(""+grades[13]);
                jTextFieldFinal.setText(""+grades[14]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==5){
                jTextFieldCourseWork.setText(""+grades[15]);
                jTextFieldMidTerm.setText(""+grades[16]);
                jTextFieldFinal.setText(""+grades[17]);
            }
            else if(jComboBoxResgisteredCourse.getSelectedIndex()==6){
                jTextFieldCourseWork.setText(""+grades[18]);
                jTextFieldMidTerm.setText(""+grades[19]);
                jTextFieldFinal.setText(""+grades[20]);
            }
        }
    }//GEN-LAST:event_jComboBoxResgisteredCourseActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        jPanelWrongCourseWork.setVisible(false);
        jPanelWrongFinalExam.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelwrongMidTerm.setVisible(false);
        
        
        if(!jTextFieldIDAdminSearch.getText().equals("")&&!jTextFieldCourseWork.getText().equals("")&&!jTextFieldFinal.getText().equals("")
           &&!jTextFieldMidTerm.getText().equals(""))
        {
            Validation v = new Validation();
            if(v.checkID(jTextFieldIDAdminSearch.getText())){
                if(v.checkGrades(jTextFieldCourseWork.getText())){
                    if(v.checkGrades(jTextFieldMidTerm.getText())){
                        if(v.checkGrades(jTextFieldFinal.getText())){
                                        Student ad = new Student();
                                        ad=ad.getStudent(Integer.parseInt(jTextFieldIDAdminSearch.getText()));
                                        if(ad!=null){
                                            double grades[]=ad.getGrades();
                                            if(jComboBoxResgisteredCourse.getSelectedIndex()==0){
                                                grades[0]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[1]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[2]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==1){
                                                grades[3]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[4]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[5]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==2){
                                                grades[6]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[7]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[8]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==3){
                                                grades[9]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[10]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[11]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==4){
                                                grades[12]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[13]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[14]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==5){
                                                grades[15]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[16]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[17]=Double.parseDouble(jTextFieldFinal.getText());
                                            }
                                            else if(jComboBoxResgisteredCourse.getSelectedIndex()==6){
                                                grades[18]=Double.parseDouble(jTextFieldCourseWork.getText());
                                                grades[19]=Double.parseDouble(jTextFieldMidTerm.getText());
                                                grades[20]=Double.parseDouble(jTextFieldFinal.getText());
                                            }


                                            if(ad.editStudent(Integer.parseInt(jTextFieldIDAdminSearch.getText()))){
                                                jLabelSuccessOrFail.setText("Updated Successfully ...! :)");
                                                resetPanel();
                                            }
                                            else
                                            jLabelSuccessOrFail.setText("Failed Updated ...! :(");
                                        }
                                        else{
                                                    jLabelSuccessOrFail.setText("Not Found Student ...! :(");
                                                    JOptionPane.showMessageDialog(null, "Not Found ID Admin ...!\n Try Again :(");
                                                    resetPanel();
                                                } // End Assign & Start Elses Checks
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Not valid Final Exam Try Again :(\nHint: Final Exam  should  between Range [0,100]  .. ;)");
                        jPanelWrongFinalExam.setVisible(true);
                    }
                        }
                       else{
                           JOptionPane.showMessageDialog(null, "Not valid Mid Term Try Again :(\nHint: Mid Term should  between Range [0,100]  .. ;)");
                           jPanelwrongMidTerm.setVisible(true);
                        }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not valid Course Work Try Again :(\nHint: Course Work should  between Range [0,100]  .. ;)");
                    jPanelWrongCourseWork.setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required Fields ... !  Please, complete them before submit ...! :(");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabelSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseClicked
        // TODO add your handling code here:
        jPanelWrongCourseWork.setVisible(false);
        jPanelWrongFinalExam.setVisible(false);
        jPanelWrongSearchKey.setVisible(false);
        jPanelwrongMidTerm.setVisible(false);
        jComboBoxResgisteredCourse.setEnabled(false);
        
        jTextFieldCourseWork.setEnabled(false);
        jTextFieldFinal.setEnabled(false);
        jTextFieldMidTerm.setEnabled(false);
        
        if(!jTextFieldIDAdminSearch.getText().equals("")){
            if(new Validation().checkID(jTextFieldIDAdminSearch.getText())){
                Student x = new Student();
                x=x.getStudent(Integer.parseInt(jTextFieldIDAdminSearch.getText()));
                if(x!=null){
                    setPanel(x);
                    jTextFieldCourseWork.setEnabled(true);
                    jTextFieldFinal.setEnabled(true);
                    jTextFieldMidTerm.setEnabled(true);
                    jComboBoxResgisteredCourse.setEnabled(true);
                    jLabelSuccessOrFail.setText("Founded :)");
                }
                else{
                        jLabelSuccessOrFail.setText("Not Found ...! :(");
                        JOptionPane.showMessageDialog(null, "Not Found ID Admin ...!\n Try Again :(");
                        resetPanel();
                    }
                }
            else{
                JOptionPane.showMessageDialog(null, "Not valid ID Admin Try Again :(\nHint: ID Admin Length should more than 4 .. ;)");
                jPanelWrongSearchKey.setVisible(true);
            }
        }
        else
        jLabelSuccessOrFail.setText("Missing Required ID Student ... !  Please, complete it before submit ...! :(");
    }//GEN-LAST:event_jLabelSearchMouseClicked

    private void jLabelSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseEntered
        // TODO add your handling code here:
        setColor(jPanel2);
    }//GEN-LAST:event_jLabelSearchMouseEntered

    private void jLabelSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSearchMouseExited
        // TODO add your handling code here:
        getColor(jPanel2);
    }//GEN-LAST:event_jLabelSearchMouseExited

    private void jLabelResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseClicked
        // TODO add your handling code here:
        jLabelSuccessOrFail.setText("Search For Student ... !");
        resetPanel();
    }//GEN-LAST:event_jLabelResetMouseClicked

    private void jLabelResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseEntered
        // TODO add your handling code here:
        setColor(jPanel3);
    }//GEN-LAST:event_jLabelResetMouseEntered

    private void jLabelResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelResetMouseExited
        // TODO add your handling code here:
        getColor(jPanel3);
    }//GEN-LAST:event_jLabelResetMouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        setColor(jPanel1);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        getColor(jPanel1);
    }//GEN-LAST:event_jLabel14MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDepart;
    private javax.swing.JComboBox<String> jComboBoxDepart1;
    private javax.swing.JComboBox<String> jComboBoxLevel;
    private javax.swing.JComboBox<String> jComboBoxLevel1;
    private javax.swing.JComboBox<String> jComboBoxResgisteredCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelReset;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelSuccessOrFail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelWrongCourseWork;
    private javax.swing.JPanel jPanelWrongFinalExam;
    private javax.swing.JPanel jPanelWrongSearchKey;
    private javax.swing.JPanel jPanelwrongMidTerm;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldCourseWork;
    private javax.swing.JTextField jTextFieldFinal;
    private javax.swing.JTextField jTextFieldGPA;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIDAdminSearch;
    private javax.swing.JTextField jTextFieldMidTerm;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldgpa;
    // End of variables declaration//GEN-END:variables
}
